### ISSUE TITLE
Calculation of residual currents field

### ISSUE THREAD

**Issue by taoansf** [pprodano/pputils#12]
Hello,

I would like to know if there is some fast way to calculate residual currents field from telemac2d output using pputils?

Thank you for your attention.

With best regards,

Taoan

**Comment by pprodano** [comment]
In pputils you get access to reading/writing telemac result files. This means you can process the output in whichever way you wish. What you do with the results is up to you. If I know exactly what you are after, I can point you in the code where you can start from.

**Comment by taoansf** [comment]
Oh, I think I was not clear with my question...

I have some experience with pputils and I already found a way to compute residuals. However, my code is so slow if compared with BlueKenue residual extraction tool.

My question is about some fast way to perform a temporal mean on selafin currents field. On my code I simply use a for loop to access each time frame on selafin file and sum the fields. After this I divide the cumulated field by the number of frames to perform the arithmetic mean.

This is a sketch of my code
#residual field from tstart to tend
slf.readVariables(tstart)
results_tstart = slf.getVarValues()
ures=results_tstart[0]
vres=results_tstart[1]
for frame in np.arange(tstart+1,tend+1):
    slf.readVariables(frame)
    results_frame = slf.getVarValues()
    uframe=results_frame[0]
    vframe=results_frame[1]
    ures=ures+uframe
    vres=vres+vframe
ures=ures/(tend-tstart+1)
vres=vres/(tend-tstart+1)

Thank you for your fast reply.

With best regards,

Taoan

**Comment by pprodano** [comment]
Hi Taoan,

Sorry for the late reply. I looked into this a bit yesterday. The readVariables method will read all the variables, for all nodes, for a particular time step. That is how I originally intended it, as it was meant to be a conversion/extraction tool. Some years later I wrote the readVariablesAtNode method, which, as you can guess, will read all variables at a given node number.

The reason your script is so slow is because you are asking readVariables method to real all the variables, for all nodes in the mesh, for all time steps in your result file. And you only use a single variable, and discard the rest. What would most suit your case is a method called readVariable, that would read a particular variable, for all nodes, for a particular time step. This method does not exist in the pputils tools, but could be written by modifying the readVariables method and restricting it to read only a particular variable (and not all variables).

If you make it work, drop me a line, and tell me how it goes.

Best,

Pat

**Comment by pprodano** [comment]
Closing the issue
